AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  inv-pdf-aws

  Sample SAM Template for inv-pdf-aws
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Runtime: nodejs12.x
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Access-Control-Allow-Headers,Origin,Accept,Content-Type,Access-Control-Request-Method, Access-Control-Request-Headers,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  CreatePdfApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: jovisco-create-invoice-pdf
      StageName: Prod


  CreatePdfFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/create-pdf/
      Handler: app.handler
      Policies:
        - AmazonS3FullAccess
        - AWSLambdaBasicExecutionRole
      Events:
        CreatePdf:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /create-pdf/{id}
            Method: post
            RestApiId:
              Ref: CreatePdfApi
